version: "3" 
services: 
    consumer: 
        image: employee-consumer
        networks: 
            - consumer-producer 
        depends_on: 
            - producer 

    producer: 
        image: employee-producer
        ports: 
            - "8081:8080" 
        networks: 
            - consumer-producer 

networks:
    consumer-producer: